const Operators = [
    "is",
    "not",
    "and",
    "or",
    "==",
    "/=",
    "=>",
    "->",
    "=",
    "<=",
    "<",
    ">=",
    ">",
    "+",
    "-",
    "*",
    "/",
    "^",
    "mod",
    "...",
    "..",
    ".",
    "in",
];

const Keywords = [
    "let",
    "as",
    "if",
    "then",
    "else",
    "do",
    "while",
    "for",
    "match",
    "with",
    "return",
    "throw",
    "try",
    "catch",
    "finally",
    "todo",
];

const Intrinsics = [
    "@bytecode",
];

const Builtins = [
    // Values
    "Boolean",
    "Number",
    "String",
    "Symbol",
    "List",
    "Map",
    "Function",
    // Predicates
    "Nothing?",
    "Boolean?",
    "True?",
    "False?",
    "Number?",
    "String?",
    "Symbol?",
    "List?",
    "Map?",
    "Function?",
    // Functions
    "default",
    "import",
    "export",
    "test",
    "assert",
    "count",
    "copy",
    "merge" ,
    "update",
    "print",
    "input",
    "help",
    "main",
];

const NodeType = {
    Module: "Module",
    Declaration: "Declaration",
    Return: "Return",
    Throw: "Throw",
    Assignment: "Assignment",
    BinaryOperator: "BinaryOperator",
    UnaryOperator: "UnaryOperator",
    ListExpression: "ListExpression",
    MapExpression: "MapExpression",
    Pair: "Pair",
    Symbol: "Symbol",
    String: "String",
    Number: "Number",
    Boolean: "Boolean",
    Nothing: "Nothing",
    IfExpression: "IfExpression",
    DoExpression: "DoExpression",
    WhileExpression: "WhileExpression",
    MatchExpression: "MatchExpression",
    ForExpression: "ForExpression",
    TryExpression: "TryExpression",
    Function: "Function",
    Case: "Case",
    ElseCase: "ElseCase",
    Call: "Call",
    Access: "Access",
    Pattern: "Pattern",
    // Token Node Types
    Identifier: "Identifier",
    Keyword: "Keyword",
    Operator: "Operator",
    Doc: "Doc",
    ExplicitTerminator: "ExplicitTerminator",
    ImplicitTerminator: "ImplicitTerminator",
    Punctuation: "Punctuation",
    Comment: "Comment",
    Whitespace: "Whitespace",
};

const Operator = {
    Range: "Range",
    Spread: "Spread",
    Or: "Or",
    And: "And",
    NotEqual: "NotEqual",
    Equal: "Equal",
    IsNot: "IsNot",
    Is: "Is",
    LessThan: "LessThan",
    LessThanOrEqualTo: "LessThanOrEqualTo",
    GreaterThan: "GreaterThan",
    GreaterThanOrEqualTo: "GreaterThanOrEqualTo",
    NotIn: "NotIn",
    In: "In",
    Add: "Add",
    Subtract: "Subtract",
    Multiply: "Multiply",
    Divide: "Divide",
    Exponentiate: "Exponentiate",
    Not: "Not",
    Positive: "Positive",
    Negative: "Negative",
};

const TokenType = {
    Symbol: "Symbol",
    String: "String",
    Number: "Number",
    Boolean: "Boolean",
    Nothing: "Nothing",
    Identifier: "Identifier",
    Keyword: "Keyword",
    Builtin: "Builtin",
    Operator: "Operator",
    Doc: "Doc",
    ExplicitTerminator: "ExplicitTerminator",
    ImplicitTerminator: "ImplicitTerminator",
    Punctuation: "Punctuation",
    Comment: "Comment",
    Whitespace: "Whitespace",
};

module.exports = {
    Operators,
    Keywords,
    Intrinsics,
    Builtins,
    NodeType, 
    TokenType,
    Operator,
};